# Generated by Django 6.0.6 on 2026-06-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.SmallIntegerField(choices=[(1, 'Nike'), (2, 'Adidas'), (3, 'Polo Ralph Lauren'), (4, 'Tommy Hilfiger'), (5, 'Lacoste'), (6, "Levi's"), (7, 'Calvin Klein'), (8, 'The North Face'), (9, 'Vans'), (10, 'Zara')])),
                ('modelo', models.CharField(max_length=100)),
                ('ano', models.IntegerField()),
                ('cor', models.SmallIntegerField(choices=[(1, 'Preto'), (2, 'Branco'), (3, 'Cinza'), (4, 'Azul'), (5, 'Vermelho'), (6, 'Verde'), (7, 'Amarelo'), (8, 'Marrom'), (9, 'Rosa')])),
                ('tamanho', models.SmallIntegerField(choices=[(1, 'PP'), (2, 'P'), (3, 'M'), (4, 'G'), (5, 'GG'), (6, 'XG')])),
                ('categoria', models.SmallIntegerField(choices=[(1, 'Camiseta'), (2, 'Camisa'), (3, 'Calça'), (4, 'Jaqueta/Casaco'), (5, 'Moletom'), (6, 'Vestido'), (7, 'Shorts/Bermuda'), (8, 'Tênis/Calçado'), (9, 'Acessório')])),
                ('foto', models.ImageField(blank=True, null=True, upload_to='peca/fotos/')),
            ],
        ),
    ]
